import type { Catalog, Config, Rule } from './config';

export type SelectionInput = { mode: 'live'; worktree: string } | { mode: 'compare'; worktree: string; sourceRef: string; targetRef: string; sourceBranch?: string; targetBranch?: string };
export type Selection = SelectionInput & { sourceOid?: string; targetOid: string; sourceLabel: string; targetLabel: string };
export type Worktree = { path: string; branch: string; head: string };
export type CommitPage = { head?: string; parent?: string; anchorParent?: string; commits: { oid: string; subject: string }[]; hasMore: boolean };
export type Repository = { root: string; commonDir: string; name: string; worktrees: Worktree[]; branches: string[]; commits: { oid: string; subject: string }[]; unstaged: number; staged: number; untracked: number; head?: string; suggestion: SelectionInput; demo: boolean };
export type Comparison = { base: string; head: string };
export type FileComparison = Comparison & { kind: 'latest' | 'head' | 'history' | 'compare'; baseLabel: string; headLabel: string };
export type FileState = { id: string; exists: boolean; mode: string; bytes: number; binary: boolean; blob?: string; gitOid?: string; omitted?: string };
export type FileVersion = { id: string; number: number; at: string; headOid: string; state: FileState; base: FileState };
export type FileHistory = { versions: FileVersion[]; nextNumber: number; head: FileState; headOid: string; states: Record<string, FileState> };
export type FileReviewRound = { id: string; number: number; version: string; comparison: FileComparison; completedAt?: string };
export type FileHistoryEntry = { id: string; number: number; completedAt?: string; current: boolean; baseLabel: string; headLabel: string };
export type LiveFile = { version: string; head: string; round: string; number: number; count: number; completed: boolean };
export type DiffLineCounts = { additions: number; deletions: number };
export type DiffContents = { oldFile: { name: string; contents: string; cacheKey: string }; newFile: { name: string; contents: string; cacheKey: string }; lineCounts: DiffLineCounts };
export type DiffFile = { patchKey?: string; patchPending?: boolean; locatedFindings?: string[]; path: string; oldPath?: string; status: string; patch: string; revision: string; additions: number; deletions: number; binary: boolean; omitted?: string; comparison?: FileComparison; round?: string; live?: LiveFile; lineCounts?: DiffLineCounts; selectionDelta?: DiffLineCounts };
export type TabletCelebration = { startedAt: number; spinMs: number; pauseMs: number; phase: 'spinning' | 'fading'; fadeMs: number };
export type Aim = { path: string; line?: number; side?: 'additions' | 'deletions'; revision?: string; comparison?: Comparison };
export type LineRange = { start: number; end: number };
export type FindingRange = LineRange & { side: 'additions' | 'deletions' };
export type CommentRole = 'reviewer' | 'agent';
export type CommentReply = { id: string; role: CommentRole; comment: string; createdAt: string };
export type Finding = { path: string; ranges?: FindingRange[]; id: string; code?: string; rule?: Rule; comment?: string; role?: CommentRole; replies?: CommentReply[]; status: 'open' | 'resolved'; createdAt: string; resolvedAt?: string; resolution?: string; comparison?: Comparison; version?: string; resolvedVersion?: string };
export type ReviewContent = { findings: Finding[]; reviewed: Record<string, string>; fileRounds: Record<string, FileReviewRound[]>; finishedAt?: string };
export type Change = { kind: 'finding'; id: string; before?: Finding; after?: Finding } | { kind: 'reviewed'; path: string; before?: string; after?: string } | { kind: 'file-rounds'; path: string; before?: FileReviewRound[]; after?: FileReviewRound[] } | { kind: 'finished'; before?: string; after?: string };
export type Operation = { id: string; label: string; at: string; changes: Change[]; strokeId?: string };
export type Review = ReviewContent & { version: 5; id: string; selection: Selection; baselineOid?: string; processedFeedback?: string[]; carriedFindingIds?: string[]; dispatchedFindingIds?: string[]; createdAt: string; updatedAt: string; checkpoint: ReviewContent; history: Operation[]; cursor: number; revision: number; fileHistory: Record<string, FileHistory> };
export type Snapshot = { review: Omit<Review, 'fileHistory' | 'fileRounds' | 'checkpoint' | 'history'>; files: DiffFile[]; dirty: boolean; warning?: string; lastDispatch?: string };
export type SnapshotUpdate = Omit<Snapshot, 'review' | 'files'> & {
  fromRevision: number;
  review: Omit<Snapshot['review'], 'findings' | 'reviewed'>;
  findings: { set: Finding[]; remove: string[] };
  reviewed: Record<string, string | null>;
  files: { set: DiffFile[]; remove: string[]; order?: string[] };
};
export type SnapshotMessage = Snapshot | SnapshotUpdate;
export type Bootstrap = { name: string; config: Config; catalog: Catalog; repo: Repository; snapshot: Snapshot; dataDir: string; configPath: string; agentApi: string };
export type Action = { type: 'shoot'; aim: Aim; code: string; from?: Aim; endLine?: number; strokeId?: string; mutationId?: string } | { type: 'comment'; aim: Aim; comment: string } | { type: 'reply'; id: string; comment: string } | { type: 'delete-reply'; id: string; replyId: string } | { type: 'erase'; aim: Aim; from?: Aim; endLine?: number; strokeId?: string; mutationId?: string } | { type: 'delete' | 'resolve' | 'reopen'; id: string; resolution?: string } | { type: 'review-file'; path: string; revision: string; reviewed?: boolean; comparison?: Comparison } | { type: 'destroy-file'; path: string; revision: string; comparison?: Comparison; mark: string } | { type: 'finish' | 'undo' | 'redo' | 'save' | 'discard' };
